# Generated by Django 2.2 on 2020-03-07 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(verbose_name='详细信息(物品信息/联系方式等)')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('image', models.ImageField(upload_to='product_pics', verbose_name='图片')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.Province', verbose_name='省')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.Province')),
            ],
        ),
    ]
